sudo: required
language: C

services:
  - docker

cache:
    directories:
      - $HOME/.cache

stages:
  - test
  - name: deploy
    # Deploy packages to PackageCloud from tags and master
    # see:
    #   * https://github.com/tarantool/tarantool/issues/3745
    #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
    # Also skip deploys for pull-requests, api and cron events.
    if: (type = push) AND (branch = master OR tag IS present) AND (env(PACKAGECLOUD_TOKEN) IS present)

env:
  global:
    - PRODUCT=tarantool-queue
    - ROCK_NAME=queue

before_script:
  - git describe --long

_deploy_to_packagecloud: &deploy_to_packagecloud
  provider: packagecloud
  username: tarantool-test
  token: $PACKAGECLOUD_TOKEN
  dist: $OS/$DIST
  package_glob: build/*.{rpm,deb}
  skip_cleanup: true
  on:
    all_branches: true # it's restricted with the condition for deploy stage

# Pack and deploy packages to PackageCloud
_packpack: &packpack
  stage: deploy
  script:
    - git clone https://github.com/packpack/packpack.git
    - packpack/packpack
    - ls -l build/
  deploy:
    - <<: *deploy_to_packagecloud
      repository: "1_10"
    - <<: *deploy_to_packagecloud
      repository: "2x"

jobs:
  include:
    - env: VERSION=1_10
      script: ./test.sh
    - env: VERSION=2x
      script: ./test.sh

    - <<: *packpack
      env: OS=el DIST=8

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
